### ISSUE TITLE
Distance is NaN

### ISSUE THREAD

**Issue by quagla** [UPC-ViRVIG/SdfLib#1]
Hello,

I am playing around with SdfLib, it's very nice and intuitive to use. However, I am sometimes getting NaN, for example from the interpolation of a unit sphere (https://github.com/mikedh/trimesh/blob/main/models/sphere.ply). Here is a minimal example that produces (many) NaNs with the aforementioned mesh. Am I doing something wrong?

```
static sdflib::OctreeSdf *sdfFunc;

static double distance(const double p[3]) {
  glm::vec3 point(p[0], p[1], p[2]);
  return sdfFunc->getDistance(point);
}

sdflib::Mesh mesh(std::string(filename).c_str());
sdflib::BoundingBox box = mesh.getBoundingBox();
sdfFunc = new sdflib::OctreeSdf(mesh, box, 8, 3, 1e-3, sdflib::OctreeSdf::InitAlgorithm::CONTINUITY, 8);

double p[3] = {0.96, 0.24, 0.24};
printf("%d\n", std::isnan(distance(p)));
```

**Comment by triter3** [comment]
Hi,

Thank you for using the library. I found that the problem was due to the normals estimation of the field during the computation of the structure. The commit 0108ac0 should solve the issue.
