### ISSUE TITLE
SdfFunction doesn't have a virtual destructor

### ISSUE THREAD

**Issue by nimrod-gileadi** [UPC-ViRVIG/SdfLib#10]
SdfFunction has some virtual methods, but doesn't have a virtual destructor. This would trigger undefined behaviour when a subclass is deleted, and it's flagged up by some compilers.

The solution is to simply add

```
virtual ~SdfFunction() = default;
```

to the header file.

**Comment by triter3** [comment]
Hi,

Thank you for the suggestion; I did not notice it. The commit [ac65b74](https://github.com/UPC-ViRVIG/SdfLib/commit/ac65b741f7c12eae65fec40164f51eef01a4b524) fixes this issue.
