### ISSUE TITLE
License

### ISSUE THREAD

**Issue by quagla** [UPC-ViRVIG/SdfLib#2]
May I ask the reason for using the CC-BY-SA-4.0 license, which is more typical for data rather than software? I am one of the developers of the open-source simulator MuJoCo, which is licensed under Apache-2.0. We are interested in using SdfLib (in particular the approximate SDF) but unfortunately our licenses are incompatible. Is there any plan to use a less restrictive license in the future?

**Comment by triter3** [comment]
We chose the CC-BY-SA-4.0 license because the paper was published under this license. We are interested that people try our library in their projects. Therefore, we decided to change the license to an MIT license.
