### ISSUE TITLE
Bounding box distance gradient is missing

### ISSUE THREAD

**Issue by quagla** [UPC-ViRVIG/SdfLib#6]
There are two issues with the bounding box:

1. The gradient is missing. I have implemented it the brach `box` in my fork please see https://github.com/quagla/SdfLib/blob/box/include/SdfLib/utils/Mesh.h#L48
https://github.com/quagla/SdfLib/blob/box/src/sdf/OctreeSdf.cpp#L116

2. The choice 

```return mBox.getDistance(sample) + glm::sqrt(3.0f) * mBox.getSize().x;```

creates a discontinuity that it's too big and prevents operations such as ray casting. This needs changing to

```return mBox.getDistance(sample, outGradient) + mMinBorderValue;``` 

as done in the other getDistance function. Both changes are in my fork, the reason why I am not creating a pull request is that the fork is several commits ahead.

**Comment by triter3** [comment]
Hi,

I completely agree with the change. I always tested ray casting with the GPU version and didn't notice that the CPU version already had this distance heuristic. You can propose a new pull request with all the changes. I have seen your other changes and am interested in integrating them.

I'm working on a new termination rule (the rule that decides if a node needs more subdivision) to cover more distance field areas. The idea is to have a requested error that depends on the distance to the object. This way, you can have more precision near the model than at further points. This new rule will allow you to compute octrees covering bigger areas without consuming more memory and computation time. If you are interested, I will notify you when it is ready.

**Comment by quagla** [comment]
Thanks for the quick reply, I will create the pull request. Thank you for looking at the other changes and yes please keep me updated!
